In [4]:
# Import the dependencies.

import pandas as pd
import gmaps
import requests
import matplotlib.pyplot as plt
# Import the API key.
from config import g_key

In [16]:
# Store the CSV you saved created in part one into a DataFrame.

data_df = pd.read_csv("weather_data/WeatherPy_vacation.csv")
data_df.head()

,Unnamed: 0,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,7,Kattivakkam,IN,84.2,scattered clouds,13.22,80.32,St. Joseph Thirumana mandapam
1,8,Mahebourg,MU,78.8,scattered clouds,-20.41,57.70,Shandrani Beachcomber Resort & Spa
2,9,Vaini,TO,80.6,broken clouds,-21.20,-175.20,Keleti Beach Resort
3,11,Ixtapa,MX,78.8,broken clouds,20.70,-105.20,Container Inn Puerto Vallarta
4,12,Bambous Virieux,MU,78.8,scattered clouds,-20.34,57.76,Casa Tia Villa